backend:
  name: github
  branch: main
  repo: jasongannon/aws
  site_domain: https://stratosphere.netlify.app
  base_url: https://stratosphere.netlify.app
  auth_endpoint: oauth
  automatic_deployments: true
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'

media_folder: "public/images/blog" 
public_folder: "/images/blog"

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "src/content/blog"  
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime" }
      - { label: "Hero Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

site_url: https://stratosphere.netlify.app # URL to the site where the content will be displayed